### ISSUE TITLE
大牛大牛可以帮我 写代码吗?

### ISSUE THREAD

**Issue by Y-Altas** [lilei-99/blog#1]
@lilei-99 可以吗？

**Comment by lilei-99** [comment]
建议拿我的这个项目练手，帮我完善一下，------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Y-Altas&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年3月5日(星期五) 晚上11:35
收件人:&nbsp;&quot;lilei-99/blog&quot;<blog@noreply.github.com&gt;;
抄送:&nbsp;&quot;lilei-99&quot;<1589814753@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;[lilei-99/blog] 大牛大牛可以帮我 写代码吗? (#1)

**Comment by Y-Altas** [comment]
不会吧，大牛就是这样 不帮人写代码？？？？？？这叫大牛？好意思？？？？？？？？？？？你怎么敢的啊！ @lilei-99
